### ISSUE TITLE
Checking for NULL pointer (attrib.c)

### ISSUE THREAD

**Issue by EmilioSchi** [h4xxel/html#2]
My compiler:
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

When i run program, return output is this: 
Segmentation fault: 11

My solution is to change two lines into attrib.c C file ( attrib_append() function ):
	if ((attrib) != NULL) {
		\*attrib = (struct HtmlAttrib\*)malloc(sizeof(HtmlAttrib));

Great job,
Emilio

**Comment by h4xxel** [comment]
Hi, I fixed a couple of memory issues and pushed the changes, could you see if your problem still persists? If it does, what input file causes the segmentation fault?  Could you attach the file so i can try it out?

**Comment by EmilioSchi** [comment]
Now the problem is solved! Thanks a lot.
